### PR TITLE
Berny interview

### PR DESCRIPTION
**Pull request by br1992**

### CODE REVIEW

**Comment by Enrico-Caporali-Paidy** [comment]
Please delete this PR @br1992. Thank you

**Comment by br1992** [comment]
Yeah, I see how this might be a little less than helpful; that's what happens when you push something out on Friday at 7pm 😬 I reverted the branch I used to open this, but I can't update the commits, likely because the PR is closed. Sorry about the hassle 🙇

**Comment by Enrico-Caporali-Paidy** [comment]
> Yeah, I see how this might be a little less than helpful; that's what happens when you push something out on Friday at 7pm 😬 I reverted the branch I used to open this, but I can't update the commits, likely because the PR is closed. Sorry about the hassle 🙇 

No problems, I can reopen the PR if that helps.

**Comment by br1992** [comment]
I'm not sure how much that will help... I can just clobber my fork once the interview feedback is finished. That should hopefully take care of the issue. I use Gitlab, so I'm not super familiar with Github

**Pull request closed without merging**
